# See LICENSE.vyoma for details

TOPLEVEL_LANG ?= verilog

PWD=$(shell pwd)

VERILOG_SOURCES = $(PWD)/up_down_counter.v               # provide your design path

TOPLEVEL := up_down_counter          # design file
MODULE   := up_down_counter_test    # test file

include $(shell cocotb-config --makefiles)/Makefile.sim

clean_all: clean
  rm -rf *.xml sim_build pycache
